name: Cypress CI/CD Pipeline

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate
      - name: Check Yarn Version
        run: yarn --version
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Run Cypress Tests
        run: yarn cypress run --headless --browser chrom