name: Cypress CI/CD Pipeline

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v4

      # Configura o Node.js na versão especificada
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      # Instala o Corepack e garante o uso da versão correta do Yarn
      - name: Setup Corepack and Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate
          yarn set version 4.6.0

      # Verifica a versão do Yarn para debug
      - name: Verify Yarn Version
        run: yarn --version

      # Instala as dependências com o Yarn correto
      - name: Install Dependencies
        run: yarn install

      # Executa os testes com Cypress
      - name: Run Cypress Tests
        run: yarn cypress run --headless --browser chrome







