# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Cypress CI/CD Pipeline

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v4

      # Configura o Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Habilita o Corepack e configura a versão correta do Yarn
      - name: Enable Corepack
        run: corepack enable

      - name: Use Specific Yarn Version
        run: corepack prepare yarn@4.6.0 --activate

      # Instala dependências com a versão correta do Yarn
      - name: Install Dependencies
        run: yarn install

      # Executa os testes com Cypress
      - name: Run Cypress Tests
        run: yarn cypress run

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v4

      # Configura o Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      # Habilita o Corepack e configura a versão correta do Yarn
      - name: Enable Corepack
        run: corepack enable

      - name: Use Specific Yarn Version
        run: corepack prepare yarn@4.6.0 --activate

      # Instala dependências com a versão correta do Yarn
      - name: Install Dependencies
        run: yarn install

      # Publica o pacote no GitHub Packages
      - name: Publish Package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


