# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Cypress CI/CD Pipeline

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v4

      # Configura o Node.js na versão especificada
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      # Ativa o Corepack
      - name: Enable and Configure Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      # Verifica a versão correta do Yarn
      - name: Check Yarn Version
        run: yarn --version

      # Instala as dependências
      - name: Install Dependencies
        run: yarn install

      # Executa os testes com Cypress
      - name: Run Cypress Tests
        run: yarn cypress run --headless --browser chrome






