# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Cypress CI/CD Pipeline

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v4

      # Configura o Node.js na versão especificada
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      # Habilita o Corepack
      - name: Enable Corepack
        run: corepack enable

      # Configura a versão correta do Yarn
      - name: Activate Yarn Version 4.6.0
        run: corepack prepare yarn@4.6.0 --activate

      # Verifica a versão do Yarn para garantir que está correto
      - name: Check Yarn Version
        run: yarn --version

      # Instala dependências usando a versão correta do Yarn
      - name: Install Dependencies
        run: yarn install

      # Executa os testes com Cypress
      - name: Run Cypress Tests
        run: yarn cypress run --headless --browser chrome





